### PR TITLE
Disable logs & debugger

### PR DESCRIPTION
**Pull request by manosim**

### CODE REVIEW

**Comment by manosim** [comment]
@JakeSidSmith I will merge it just to mobile for now since I am not sure if everyone agrees on this one.

**Comment by JakeSidSmith** [comment]
All or nothing... plus no-debugger

**Comment by manosim** [comment]
Having logs in react native apps makes it really really slow and it is vital to merge this. In my opinion it should also be applied to web apps too but this requires further discussion?

**Comment by JakeSidSmith** [comment]
Let's discuss it real quick then.

**Pull request merged**
