### PR TITLE
Use es6 module syntax

### PR DESCRIPTION
**Pull request by pmg103**

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:...

**Comment by ekonstantinidis** [comment]
:shipit:

**Comment by weargoggles** [comment]
this allows or demands it?

**Comment by JakeSidSmith** [comment]
:sparkles: @weargoggles Allows. :)

**Comment by JakeSidSmith** [comment]
Could you also, bump us to `1.1.0` please? @pmg103

**Pull request merged**
